//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PagosApp
{
    public partial class Usuario
    {
        public Usuario()
        {
            this.RolesUsuarios = new HashSet<RolesUsuario>();
        }
    
        public int id_usuario { get; set; }
        public string nombre { get; set; }
        public string clave { get; set; }
        public string nombre_completo { get; set; }
        public bool activo { get; set; }
    
        public virtual ICollection<RolesUsuario> RolesUsuarios { get; set; }
    }
    
}
